feat: list 인기순과 오름차순으로 정렬
qmit-pro/radio-station pull request #12
Opened 2022-11-02 07:56 UTC by hmds1606

list를 인기순과 가나다순으로 선택했을 때 필터해주는 기능 추가했습니다!

[
![image](https://user-images.githubusercontent.com/104013908/199431633-2c5ee160-d64a-4e5b-ae8c-18f18597f565.png)
](url)

2022-11-02 08:07 UTC, KJoobin commented on src/containers/radio-station-list-container.tsx
> +      );
API 에서는 정렬한값을 받을수 없나요? 왜 프론트에서 직접 하시는거에요??

2022-11-02 08:13 UTC, hmds1606 commented on src/containers/radio-station-list-container.tsx
> +      );
api에서 가공해서 오는 것보다 데이터 그대로 받아와서 원하는 곳에서 가공해서 쓰고싶어서 그랬습니다!
api 폴더에서 작업하는 걸로 변경할까요??

2022-11-02 08:14 UTC, KJoobin commented on src/containers/radio-station-list-container.tsx
> +      );
API 를 통해 정렬하는것으로 해야할거같아요...! 저번처럼, 페이지네이션 을 하려면 클라이언트에서 정렬해서는 하기 어렵다고 생각합니다.

2022-11-02 08:17 UTC, hmds1606 commented on src/containers/radio-station-list-container.tsx
> +      );
네 변경해보겠습니다:)

2022-11-02 08:31 UTC, hmds1606 commented on src/containers/radio-station-list-container.tsx
> +      );
변경해서 다시 push 했습니다

2022-11-02 08:39 UTC, KJoobin commented on src/containers/radio-station-list-container.tsx
> +    if (value === "가나다순") setRadioList(ascRadioList);
필요한 데이터만 부르면 될거같습니다! 사용하지 않을 데이터까지 호출하는건 좋지않아보입니다.

2022-11-02 08:39 UTC, KJoobin commented on src/apis/list-api.ts
> +    );
pop?limit=20 이후에 sort 로직이 있으면, 20개중에서만 sort 되지 않을까요??
0\~19 번째 인덱스를 vote 로 sort 한 값과
  0\~39 번째 인덱스를 vote 로 sorting 한 값의 0\~19번째 인덱스가 동일하다고 볼수있나요?

2022-11-02 09:11 UTC, hmds1606 commented on src/containers/radio-station-list-container.tsx
> +    if (value === "가나다순") setRadioList(ascRadioList);
네!

2022-11-02 09:11 UTC, hmds1606 commented on src/apis/list-api.ts
> +    );
동일하지 않습니다. 수정하겠습니다!

2022-11-03 00:58 UTC, KJoobin requested changes

2022-11-03 00:58 UTC, KJoobin commented on src/apis/list-api.ts
>  export const popularListApi = () =>
getListApi 와 popularListApi 를 하나로 합칠수 있을것 같아요!

2022-11-03 00:58 UTC, KJoobin commented on src/containers/radio-station-list-container.tsx
> +      const popularList = await popularListApi();
한국말로 코딩하면, encode, decode 환경에서 문제가 생길수도 있을것 같습니다.

2022-11-03 01:33 UTC, hmds1606 commented on src/apis/list-api.ts
>  export const popularListApi = () =>
네! 합쳐서 다시 push 했습니다!

2022-11-03 01:33 UTC, hmds1606 commented on src/containers/radio-station-list-container.tsx
> +      const popularList = await popularListApi();
영어로 바꾸겠습니다

2022-11-03 01:36 UTC, hmds1606 commented on src/apis/list-api.ts
>  export const popularListApi = () =>
limit을 지우면 전체목록이 다 보여서 20개만 보이도록 설정한 것입니다!

2022-11-03 01:38 UTC, hmds1606 commented on src/apis/list-api.ts
> +  fetch(`http://all.${commonUrl}/stations/byname/pop?order=${order}`).then(
if (value === "names") {
      const ascRadioList = await getListApi(**"name&limit=20"**);
      setRadioList(ascRadioList);
    } else if (value === "votes") {
      const popularList = await getListApi(**"votes&reverse=true&limit=20"**);
      setRadioList(popularList);
    }

네 거기는 없애고 여기로 넘겨줬습니다!

2022-11-03 05:43 UTC, hmds1606 commented on src/apis/list-api.ts
> +  fetch(`http://all.${commonUrl}/stations/byname/pop?order=${order}`).then(
수정 후 push 했습니다!

2022-11-03 05:46 UTC, KJoobin approved these changes
훨씬 깔끔한거같아요!

2022-11-03 05:46 UTC, KJoobin commented on src/apis/list-api.ts
> +};
default value 를 사용하면 더 간단하게 해결할수 있습니다.
```ts
type GetListApi = (args: {
  order: string;
  reverse?: boolean;
  limit?: number;
}) => Promise<RadioList[]>;

export const getListApi: GetListApi = ({ order, reverse = false, limit = 20 }) => {
  return fetch(
    `http://all.${commonUrl}/stations/byname/pop?order=${order}&reverse=${reverse}&limit=${limit}`
  ).then((res) => res.json());
};

```

2022-11-03 05:49 UTC, hmds1606 commented on src/apis/list-api.ts
> +};
감사합니다!

2022-11-03 05:49 UTC, merged