feat: add list(use api)
qmit-pro/radio-station pull request #8
Opened 2022-10-26 06:17 UTC by hmds1606

feat: add list(use api)
오픈API 사용하여 라디오 방송국 리스트 뿌리는 작업 진행

2022-10-26 06:33 UTC, KJoobin commented on src/containers/radio-station-list-container.tsx
> +    const callAPI = async () => {
이름을 무엇을 위한 API 요청인지 로 적어주시면 더 좋을거같아요

2022-10-26 06:33 UTC, KJoobin commented on src/index.tsx
> -  <React.StrictMode>
StrictMode 는 왜 제거하셨나요?

2022-10-26 06:33 UTC, KJoobin commented on src/containers/radio-station-list-container.tsx
> +  });
sort 가 문제없이 되나요?? 의도대로 안될거같아요..!

2022-10-26 06:33 UTC, KJoobin commented on src/containers/radio-station-list-container.tsx
> +  );
> filter((element, index, array) => { /* … */ } )

filter 의 3번째인자는 callback 이 아닌 array 입니다!

redioList 와 radioStationList 는 무엇이 다른거에요?

2022-10-26 06:49 UTC, hmds1606 commented on src/containers/radio-station-list-container.tsx
> +    const callAPI = async () => {
네!

2022-10-26 06:51 UTC, hmds1606 commented on src/index.tsx
> -  <React.StrictMode>
콘솔찍을 때 두번씩 찍혀서 검색해보니까 StricMode 지우면 된다고해서 지웠습니다..!

2022-10-26 06:53 UTC, KJoobin commented on src/index.tsx
> -  <React.StrictMode>
왜 존재하는걸까요?

2022-10-26 06:56 UTC, hmds1606 commented on src/containers/radio-station-list-container.tsx
> +  });
네 잘됩니다! 근데 아랍어 같은거는 맨 앞글자 알파벳을 인식을 못해서 맨 뒤로 가는거같아요

2022-10-26 07:23 UTC, hmds1606 commented on src/containers/radio-station-list-container.tsx
> +  );
radioList에 이름이 중복되는 애들이 있어서 그걸 걸러낸게 radioStaitonList 입니다!

2022-10-26 07:33 UTC, KJoobin commented on src/containers/radio-station-list-container.tsx
> +  );
name 은 유니크 한 값이 아니기때문에 동일한 이름이 있을수도 있지않나요?!

2022-10-26 07:36 UTC, hmds1606 commented on src/containers/radio-station-list-container.tsx
> +  );
같은 name안에 들어간 내용들이 동일해서 그러면 그냥 하나의 방송국만 보여주고 싶어서 그랬습니다! 다보여주는 걸로 수정할까요?

2022-10-26 07:37 UTC, KJoobin commented on src/containers/radio-station-list-container.tsx
> +  );
의도치않게, 이름은 동일한데 다른 방송국이 삭제될 수 있을거같아요! 유니크한값으로 필터링을 하는게 좋을것 같습니다

2022-10-26 07:39 UTC, hmds1606 commented on src/containers/radio-station-list-container.tsx
> +  );
네!

2022-11-01 04:55 UTC, KJoobin requested changes

2022-11-01 04:55 UTC, KJoobin commented on src/App.tsx
> +        <Route path="/radio-stations/:stationuuid" element={<DetailPage />} />
잘하셨습니다! 👍

2022-11-01 04:55 UTC, KJoobin commented on src/containers/radio-staiton-detail-contatiner.tsx
> +      .then(setRadioStation);
api 관련된 로직은 apis 폴더에서 관리하면 좋을거같아요!

2022-11-01 04:55 UTC, KJoobin commented on src/containers/radio-station-list-container.tsx
>    );
중복되는 radio list 를 삭제하는건 추후에 다시 진행하죠!! (지금 방식은 조금 비효율적인거 같아요!)

2022-11-01 04:55 UTC, KJoobin commented on src/containers/radio-station-list-container.tsx
> +    navigation(`/radio-stations/${stationuuid}`, { state: { stationuuid } });
state 를 같이 보내시는 이유가 있으신가요?

2022-11-01 05:16 UTC, hmds1606 commented on src/App.tsx
> +        <Route path="/radio-stations/:stationuuid" element={<DetailPage />} />
감사합니다!

2022-11-01 05:16 UTC, hmds1606 commented on src/containers/radio-staiton-detail-contatiner.tsx
> +      .then(setRadioStation);
넵!

2022-11-01 05:17 UTC, hmds1606 commented on src/containers/radio-station-list-container.tsx
>    );
네 그럼 삭제하고 나중에 하겠습니다!

2022-11-01 05:19 UTC, hmds1606 commented on src/containers/radio-station-list-container.tsx
> +    navigation(`/radio-stations/${stationuuid}`, { state: { stationuuid } });
아 이게 지금 진행 중인 작업인데 stationuuid를 가지고 디테일 페이지에서 사용하고 싶어서 이것저것 해보다가 남아있는 상태입니다..ㅎ
변경 가능성이 많은 부분입니다!

2022-11-01 06:37 UTC, merged